### ISSUE TITLE
Proposte sito (da Ilaria)

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#1]
sul sito (mi piacerebbe pure il logo di mappina ma solo se ci appizza, ovvero se è coerente) poi:
1. se mettiamo i riquadri con le scritte devono rimandare a quelcosa: tipo pulsanti, io ci clicco sopra ma non esce niente
2. lo statuto va messo nel menù
3. dovevamo (colpa mia) fare una lista di tutti i format e i video (soprattutto del capitan borruso) sull'uso e apertura dei dati, tipo lettera di accesso civico per i comuni, e altre cose (forse è il caso di fare un foglio drive dove iniziamo a inrerire i link?)
4. nelle info ci vuole il codice fiscale

**Comment by ilacopperfild** [comment]
Suggerimenti HomePage
- colore menu azzurro, preferirei blu #003366 in trasparenza
- testo (non svengo per il Font) ma se non è nei titoli mettiamolo light
- eviterei le evidenziazioni in giallo, sembrano dei refusi
- i titoli devono essere tutti della stessa dimensione (chi siamo è più grande di progetti...)
- nei titoli levare tutte le frecce verso il basso (che si capisce lo stesso) e anche la linea di separazione (che a volte c'è a volte non c'è).

CHI SIAMO:
- nelle immagini eviterei le cornici, sembriamo tutti morti ... , le metterei piatte su fondo diverso (magari blu trasparente con scritte bianche)  ma va bene.  Cliccando sulle immagini si dovrebbe andare ad una sola pagina con tutte immagini e piccola bio di ognuno (pagina da collegare al menu). Avevamo un file presentiamoci o una mail?

I NOSTRI VALORI
- scritte bianche su  fondo blu (trasparenza 70%). Poichè usiamo delle icone che normalmente rimandano a qualcosa (io ci clicco sempre sopra..) in prospettiva dobbiamo usare "partecipazione" "trasparenza" "open data" "collaborazione" come tag delle cose che facciamo e che riportiamo nel blog.
  Es "una ondina al comune di napoli", tag open data, collaborazione.

**Comment by giuragu** [comment]
Ho risolto il punto "nei titoli levare tutte le frecce verso il basso (che si capisce lo stesso) e anche la linea di separazione (che a volte c'è a volte non c'è)"

**Comment by giuragu** [comment]
Ho risolto il punto "i titoli devono essere tutti della stessa dimensione". Rimane di minori dimensioni il titolo "ultime notizie da blog.ondata.it".

**Comment by ilacopperfild** [comment]
@giuragu riusciamo pure a risolvere la questione delle immagini, senza quella cornice da tomba?

**Comment by giuragu** [comment]
@ilacopperfild ok ci provo :)... Dicevi "le metterei piatte su fondo diverso (magari blu trasparente con scritte bianche)". Una cosa del genere o ho capito male? Per il momento come colore di sfondo ho utilizzato il medesimo della navbar superiore
![img](https://cloud.githubusercontent.com/assets/12112056/17594581/258ff64a-5fea-11e6-8d5f-2dedcf81003c.png)

**Comment by nelsonmau** [comment]
@giuragu e @ilacopperfild a me la versione blu non piace molto... troppo contrasto...

**Comment by nelsonmau** [comment]
@giuragu ho sistema i titoli della sezione news, guarda come ho fatto e ti addentrerai nel meraviglioso mondo del javascript :) https://github.com/ondata/ondatawebsite/commit/9c12a08d7a61ccbb694ce54784cf2c29ad5e7537

**Comment by ilacopperfild** [comment]
no mi riferivo a tutta la striscia con le immagini non a singola immagine, ma lasciamo tutto in bianco

**Comment by nelsonmau** [comment]
questo filone lo chiudiamo, si riferisce al vecchio sito..
