### ISSUE TITLE
pulsante "LEARN MORE" non funzionante

### ISSUE THREAD

**Issue by lorenzoperone** [ondata/ondatawebsite#14]
Forse si può togliere
![schermata 2017-02-13 alle 12 40 50](https://cloud.githubusercontent.com/assets/5204799/22882092/c9e02dfa-f1e9-11e6-96e6-a50a391527be.png)

**Comment by nelsonmau** [comment]
fixed https://github.com/ondata/ondatawebsite/commit/55b8e0be1d2774e8726331e22be3c32d1e5a8cde

grazie!
