### ISSUE TITLE
Progetti In homepage + pagina

### ISSUE THREAD

**Issue by ilacopperfild** [ondata/ondatawebsite#18]
Ogni progetto deve avere come immagine il logo (albopop...) e dovrebbe rimandare ad una pagina dedicata ed eventualmente link a blog (se c'è articolo). 
Tra i progetti inseriamo anche le iniziative/eventi.
In menu apriamo una pagina con lista Progetti /iniziative/ sostegni.
Tra le iniziative International open data Day 2016
http://www.regione.campania.it/it/news/eventi-tcjacpax/open-data-day-2016

hakathon Milano@work
http://www.digitaldistrict.it/it/eventi/hackathon/milano-work

tra i sostegni 
ODS 2016 
Sbilanciamoci

**Comment by nelsonmau** [comment]
allora intanto farei così
in hp non mettiamo i progetti, ma usiamo quelli spazio per mettere tipo

| progetti | strumenti | risorse |

ognuno di questi punta a una pagina dedicata

che ne dici?

**Comment by nelsonmau** [comment]
@ilacopperfild  la prima versione della pagina progetti è qui http://ondata.it/progetti.html

che te ne pare?

**Comment by ilacopperfild** [comment]
mi piace, va tutto bene (logicamente con | progetti | strumenti | risorse | al posto di web design | icon| grafic design)

**Comment by nelsonmau** [comment]
nono, progetti strumenti e risorse in home page

qui invece tipologie di progetti e cioè: | piattaforme | approfondimenti | eventi |

**Comment by ilacopperfild** [comment]
Allora non ho capito
la pagina progetti.html va in menù?

**Comment by nelsonmau** [comment]
sì
non dovrebbe?

**Comment by nelsonmau** [comment]
verrebbe così 

![ondatamenu](https://cloud.githubusercontent.com/assets/1769578/22927026/7779cfe6-f2af-11e6-8788-8fd8c481eb95.png)

**Comment by ilacopperfild** [comment]
ma poi sotto niente?

**Comment by nelsonmau** [comment]
@ilacopperfild sotto così 
![ondata_boxhp](https://cloud.githubusercontent.com/assets/1769578/22927736/3eae2014-f2b3-11e6-8c94-523f1d83342a.png)

**Comment by ilacopperfild** [comment]
:) 
i colori Azzurro/ bianco/ grigio (non quel bianco sporco)
fai i pulsanti in grigio chiaro #CCCCCC  /testo nero
o Grigio scuro #666666 / testo bianco

**Comment by nelsonmau** [comment]
quale preferisci ?

![ondata-boxhp_blueblack](https://cloud.githubusercontent.com/assets/1769578/22928270/d643fc3a-f2b5-11e6-940d-7b6f2ceaeac3.png)
![ondata-boxhp_grayblue](https://cloud.githubusercontent.com/assets/1769578/22928271/d6474480-f2b5-11e6-8867-8e70644381d9.png)

**Comment by ilacopperfild** [comment]
la seconda, oppure sulla seconda inverti blu sopra, grigiolino scritta nera sotto

**Comment by nelsonmau** [comment]
non si può invertire, sto cercando di attenermi rigorosamente alla grafica prevista nel tema, per evitare di fare paciocchi :)

**Comment by nelsonmau** [comment]
teniamo la seconda allora dai
in serata metto tutto online

**Comment by ilacopperfild** [comment]
occhei

**Comment by nelsonmau** [comment]
finished...

**Comment by ilacopperfild** [comment]
vediamo
