### ISSUE TITLE
Box & footer in homepage

### ISSUE THREAD

**Issue by ilacopperfild** [ondata/ondatawebsite#19]
Ogni riga deve essere trattata alternativamente con colori diversi, bianca(grigia) e blu.
I box Partecipazione/trasparenza/open Data/ collaborazione vanno in blu con le scritte e icone bianche
Nel footer al posto dei soci mettiamo i last tweet

**Comment by nelsonmau** [comment]
fatti entrambi, https://github.com/ondata/ondatawebsite/commit/c4a99118aee78978623e7b53333cd2e5bc034bc2

**Comment by ilacopperfild** [comment]
@nelson se fai i box Partecipazione/trasparenza/open Data/ collaborazione vanno in blu con le scritte e icone bianche viene meglio la homepage
