### ISSUE TITLE
Pagine "Risorse": che risorse aggiungiamo?

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#2]
è nella root e si chiama `risorse.html`

Per adesso ho aggiunto i confini amministrativi italici e europei. 
Quali aggiungiamo? Proponete please!

**Comment by aborruso** [comment]
@nelsonmau io farei un repo a parte. Che ne pensi?

**Comment by nelsonmau** [comment]
e che ci mettiamo dentro? per il momento non c'è nulla e io mi immaginavo inizialmente una raccolta di link... poi però se altri hanno tempo di lavorarci, perché no?

**Comment by nelsonmau** [comment]
chiudo qui
