### ISSUE TITLE
Pagina Progetti

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#20]
- sistemare descrizioni singoli progetti
- sistemare classi per filtro per tipologia
- tipologie previste: | piattaforme | eventi | approfondimenti |

**Comment by nelsonmau** [comment]
ho aggiunto campagne... mi pare che ora ci sia tutto

mancano però le varie attività di formazione
e anche le reti di soggeti con i quali collaboriamo (libera, actiondaid...)
sui partner forse serve pagina specifica...

**Comment by ilacopperfild** [comment]
allora per i progetti dividiamo

Piattaforme
- confiscatibene
-RT
-sbilanciamoci
- albo pop (no va qui?)

Ricerche (Approfondimenti)
- dati alle fiamme
- open data companies 
- Confiscated Goods

Hackathon, Open Data Day, Raduni (Eventi)
- Milano@ork
- Mentoring Hackathon “The big Hack” – Roma
- International Open Data Day 2016
- ods16

Formazione

Campagne??

qui quello che abbiamo fatto nel 2016

poi metterei il video di elena Ripresi Bene in Risorse

In ogni progetto/hackathon/... dobbiamo mettere anche il link al blog

poi possiamo usare Partecipazione/Trasparenza/Open Data/Collaborazione (quelli del box nell'home page)  come tag delle pagine dei progetti/eventi/...così cliccando ad esempio su Open Data (in home page) si aprono sotto (Hackaton, progetti...) oppure su trasparenza (laura strano, albo pop...) Partecipazione (confiscatibene...) e collaborazione (libera, action aid, mappina, Dataninja...)

**Comment by nelsonmau** [comment]
finita, per adesso è ok, poi vedremo
grazie a tutti
