### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#21]
c'è da capire se metterlo in funzione o toglierlo e lasciare la mail

poi devo chiedere ad andy/alessio

**Comment by nelsonmau** [comment]
@jenkin @aborruso: che ne dite? fare la pena mettere in funzione il form? la pagina è nella root, contact.html, ma poi c'è anche la cartellina /contactform/

su questo palla a voi

**Comment by jenkin** [comment]
@nelsonmau caccia i soldi e lo avrai: https://github.com/ondata/ondatawebsite/blob/gh-pages/contactform/readme.txt

**Comment by nelsonmau** [comment]
@jenkin e non possiamo fare copia-incolla di questo? https://github.com/factcheckersit/website/issues/6

**Comment by nelsonmau** [comment]
@jenkin hai fatto copia e incolla di questo? https://github.com/factcheckersit/website/issues/6

**Comment by jenkin** [comment]
Facciamo che tu pensi a inserire quel codice html e js e poi io penso a farlo funzionare appoggiando il php sul server di ondata...
