### ISSUE TITLE
Ricollocazione attività e Tag

### ISSUE THREAD

**Issue by ilacopperfild** [ondata/ondatawebsite#24]
Ho ricollocato le attività: piattaforma/ricerche/Hackathon/Opendataday/...  e risorse che però va in una pagina a se e ridefinito i tag-box in homepage: artecipazione/trasparenza/opendata/Formazione mettendo le collaborazioni a parte (saranno linkati dentro le attività e  in chi siamo, mettiamo anche con chi lavoriamo con i loghi di libera, action aid....)
li trovate qui:
https://docs.google.com/a/ondata.it/spreadsheets/d/1U3mydvDTc9IiAFVNWMIzU7OxnqidszNs_smnJ5B8KQ0/edit?usp=sharing
Ora bisogna mettere tutti i progetti, le attività, i tag e le collaborazioni

**Comment by nelsonmau** [comment]
fatto, ottimo!
