### ISSUE TITLE
Foto slider

### ISSUE THREAD

**Issue by dontyna** [ondata/ondatawebsite#25]
Sostituirei 

- quella della slide "chi siamo" che mi sembra un po' oscura, tipo hacker che lavorano nella notte. Se ci sono foto di gruppo belle sarebbe meglio.
- quella della slide "cosa facciamo" perché non ha una buona risoluzione.

Se c'è un dropbox con foto posso aiutare a scegliere.

**Comment by nelsonmau** [comment]
c'è un flickr https://www.flickr.com/photos/ondatait/

il direttore della fotografia è @lorenzoperone :)

**Comment by nelsonmau** [comment]
@dontyna ok cambiato le foto. Check please su http://ondata.it
