### ISSUE TITLE
Voce contact

### ISSUE THREAD

**Issue by dontyna** [ondata/ondatawebsite#27]
Tutte le voci sono in italiano, quindi anche questa dovrebbe essere "Contatti" o "Dove siamo" visto che poi si apre una mappa. A quel punto manca un form di contatti o un modo per contattare l'associazione.

**Comment by nelsonmau** [comment]
c'è il form in basso :)

la voce in italiano invece la sistemo subito

**Comment by nelsonmau** [comment]
done :) bc01534e56d3280cc059a4f98e1276d04ceb0266
