### ISSUE TITLE
Slider da mobile

### ISSUE THREAD

**Issue by dontyna** [ondata/ondatawebsite#28]
Non si leggono le scritte.

**Comment by nelsonmau** [comment]
da mobile è volutamente oscurato dal tema.
quello che possiamo fare è renderlo più o meno così
(per non perdere il css lo copio qui) 

```
div.flex-caption {
    display:inline !important;
    margin: -45px -45px -165px 10px;
    width: 100%;
    padding: 15px;
}

div.flex-caption h3, div.flex-caption p {
  font-size:1rem !important;
}
section.callaction {
  margin-top:35px;
}
```

![ondataslidermobile](https://cloud.githubusercontent.com/assets/1769578/23020463/88f7cd88-f447-11e6-8e4d-cfe349e133f1.png)

**Comment by nelsonmau** [comment]
@dontyna visto che il sito è provvisorio, chiudo questa issue come #wontfix e amen
abbi pazienza :)
