### ISSUE TITLE
Da aggiungere: Mentoring Hackathon “The big Hack” – Roma

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#29]
@jenkin mi dai please:

1) foto/immagine
2) descrizione
3) url/link

così lo mettiamo tra gli eventi in questa pagina http://ondata.it/progetti.html

grazie

**Comment by nelsonmau** [comment]
(se vuoi, metti direttamente tu in coda nell'html)

**Comment by jenkin** [comment]
Fatto tutto in quattro commit (uno per eliminare l'immagine caricata nel posto sbagliato)...
