### ISSUE TITLE
HP cover inguardabile da mobile 

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#3]
Sistemare menu...

![screenshot_2016-08-08-15-11-30](https://cloud.githubusercontent.com/assets/1769578/17480932/a79b5b2e-5d7a-11e6-8469-95b64a9f79b8.png)

**Comment by nelsonmau** [comment]
ora sembra funzionare dopo 8a8f86ece3b65bb7596dc2b74bff70df1404eb82 e 898ee15d5d9319917c8ed8efa4881626cdeda6a6

**Comment by jenkin** [comment]
Io metterei un video (desktop) e una gif animata (mobile) usando una roba del genere: https://github.com/VodkaBears/Vide :)
