### ISSUE TITLE
Inserire lo statuto dell'associazione

### ISSUE THREAD

**Issue by aborruso** [ondata/ondatawebsite#30]

**Comment by nelsonmau** [comment]
ho messo l'originale firmato 3632c227031d87a19cc56d30d4ceed1993fb7a61
se ok lo linko in hp

**Comment by aborruso** [comment]
ok

**Comment by nelsonmau** [comment]
statuto nel footer everywhere 7865b54a189c5e36021c8184cdd3c729ce3d2e72

@dcrespi: il link diretto al download is qui http://ondata.it/docs/ondata-statuto.pdf

grazie della segnalazione :-)
