### ISSUE TITLE
Pagina About

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#32]
ho fatto una pagina about
http://ondata.it/about

@aborruso ci guardi e mi dici se ok?
se sì metto in navbar

graz

**Comment by nelsonmau** [comment]
@aborruso pronunciati pls

**Comment by nelsonmau** [comment]
@ilacopperfild per favore dai un'occhiata a questa pagina
http://ondata.it/about.html

se ti va bene la mettiamo nella barra di navigazione
sennò dimmi qui cosa cambiare

grazie

**Comment by aborruso** [comment]
@nelsonmau per me lo puoi pubblicare.

Io aggiungerei in testa a tutto:

> onData è un'associazione per la promozione della trasparenza e della cultura dei dati attraverso le competenze digitali e il giornalismo investigativo.

grazie

**Comment by ilacopperfild** [comment]
marò che tristezza, neanche una foto...

Il giorno 3 marzo 2017 10:12, Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by nelsonmau** [comment]
@ilacopperfild hai ragione, ci lavoro separatamente...

**Comment by nelsonmau** [comment]
ho fatto un'unica pagina con contatti

trovate tutto qui http://ondata.it/contact.html

chiudo la issue
grazie :)

**Comment by ilacopperfild** [comment]
soci di ondata in ordine alfabetico

2017-03-03 11:02 GMT+01:00 Andrea Nelson Mauro <notifications@github.com>:

**Comment by nelsonmau** [comment]
@ilacopperfild giusto

controlli se manca qualcuno/a?


Enrico Bergamini, 
Andrea Borruso, 
Nicola Bruno, 
Alessio Cimarelli, 
Mara Cinquepalmi, 
Donata Columbro,
Carlo Felice Dalla Pasqua, 
Gianluca De Martino, 
Elena Iannone, 
Paolo Mainardi,
Stefano Mainardi, 
Andrea Nelson Mauro, 
Marco Montanari, 
Franco Morelli, ,
Vincenzo Patruno. 
Lorenzo Perone, 
Giuseppe Ragusa, 
Patrizia Saggini, 
Massimo Santi
Piero Savastano,
Laura Strano,
Davide Taibi, 
Ilaria Vitellio, 
Massimo Zotti,

**Comment by ilacopperfild** [comment]
appost

Il giorno 3 marzo 2017 11:24, Andrea Nelson Mauro <notifications@github.com>
ha scritto:

**Comment by nelsonmau** [comment]
http://ondata.it/contact.html corretto
