### ISSUE TITLE
Gestione branch

### ISSUE THREAD

**Issue by jenkin** [ondata/ondatawebsite#33]
Propongo di usare il modello [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/) per gestire il repo, impostando due branch persistenti:

* master: la branch in produzione servita da github sul dominio ondata.it (l'impostazione va cambiata nei settings: GitHub Pages > Source);
* develop: le modifiche temporanee non visibili sul sito, su cui lavorare e da approvare prima di metterle in produzione (facendo una merge sulla master).

La branch gh-pages verrebbe cancellata.

**Comment by nelsonmau** [comment]
sì ok, sistemo a breve... il casino è colpa mia

**Comment by nelsonmau** [comment]
sai che non riesco?
in locale faccio checkout master e poi poi merge gh-pages ma non accade nulla

**Comment by jenkin** [comment]
Forse serve prima un git fetch?

**Comment by jenkin** [comment]
Ma no, vedo ora, mi pare abbia funzionato, no?

**Comment by nelsonmau** [comment]
fetch not work

se hai tempo fallo te

**Comment by nelsonmau** [comment]
sennò se resta pending, appena ho tempo di guardo bene e con calma

**Comment by jenkin** [comment]
Risolto, ora la branch pubblicata è la master (che è anche una branch protetta), la gh-pages non c'è più, mentre il lavoro di sviluppo viene fatto sulla develop. Aggiunto anche il versionamento semantico. Come detto, seguiamo il modello [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/).
