### ISSUE TITLE
Invertitore di tabelle pivot

### ISSUE THREAD

**Issue by jenkin** [ondata/ondatawebsite#34]
Il problema è semplice: una tabella ben fatta (nel senso della teoria relazionale) separa la struttura dal contenuto, per cui non ci sono *valori* delle variabili nelle intestazioni delle colonne.

```
Id	Anno	Numero
a	2016	1
b	2016	2
c	2016	3
a	2017	3
b	2017	2
c	2017	1
```

In un uso tipico della tabella pivot, però, la tabella originale viene *girata* in modo da esplicitare l'andamento temporale (in questo caso la funzione di aggregazione è di fatto l'identità).

```
	2016	2017
a	1	3
b	2	2
c	3	1
```

Molto spesso le tabelle che si trovano in report e nei portali open data hanno proprio questa forma. Sono human-readable, ma richiedono una trasformazione per essere realmente machine-readable: una sorta di tabella pivot inversa.

Curiosamente questa funzione non è tra quelle bell'e pronte dei fogli di calcolo, cercate per esempio "reverse pivot table" e scoprirete che si parla di una funzione di una vecchia versione di excel non più funzionante. Anche per questo negli ultimi tempi diverse persone mi hanno posto il problema e non sono mai riuscito a fornire risposte convincenti e soprattutto alla portata di non programmatori.

Da un punto di vista algoritmico, l'operazione è banalissima. [L'ho implementata](https://github.com/ondata/ondatawebsite/blob/feature/pivot-reverser/strumenti/pivot-reverser.js) in pochi minuti usando [UnderscoreJS](http://underscorejs.org/) nella [pagina](https://github.com/ondata/ondatawebsite/blob/feature/pivot-reverser/strumenti/pivot-reverser.html) `strumenti/pivot-reverser.html` nella [branch](https://github.com/ondata/ondatawebsite/tree/feature/pivot-reverser) `feature/pivot-reverser`.

Per metterla a disposizione del mondo (ovvero farne il merge sulla master) è necessario un po' di lavoro sulla pagina per renderla più *accattivante* e utile da un punto di vista di UX (niente di che, ma almeno sfruttare bootstrap). Magari permettere all'utente di scegliere il separatore di campo per i dati in ingresso e in uscita (ora di default c'è il TAB, ma si può aggiungere almeno la virgola e il punto e virgola). E poi naturalmente fare qualche test.

**Comment by aborruso** [comment]
@jenkin questa spaccherà :)

Enri ed io abbiamo scritto due post ([qui](https://medium.com/@enricobergamini/creating-non-numeric-pivot-tables-with-python-pandas-7aa9dfd788a7#.v17ze778o) e [qui](https://medium.com/mai-piu-senza/creating-non-numeric-pivot-tables-with-python-pandas-recipe-two-7fb6cf118fb6#.llao6jf10)) ispirati a questa esigenza che è veramente forte. 

Con un'interfaccia web cambia tutto. Complimenti!

**Comment by jenkin** [comment]
Ho invitato Enrico a collaborare... :) Io farei una piccola call to action in ML, finire di sviluppare questo tool è un task molto semplice, ma anche molto istruttivo per chi è alle prime armi e vuole sporcarsi le mani per imparare.

**Comment by ebergam** [comment]
@aborruso Io e @jenkin Ne abbiamo parlato circa 18 ore fa a Termini, e l'ha già fatto.. Che spettacolo, grande Ale :)

**Comment by ebergam** [comment]
@jenkin UX messa a posto, un'altra idea sarebbe di riuscire a farlo andare in entrambi i versi, cioè sia così che diciamo nel "verso" mio e @aborruso

**Comment by jenkin** [comment]
@ebergam messa a posto dove?!? :) Il *vostro* verso è quello delle tabelle pivot standard, tranne il fatto che di solito non c'è la funzione di aggregazione *identità* tra le scelte... sarebbe molto semplice implementarla, ma richiede più input da parte dell'utente: oltre alla tabella, anche la variabile da mettere in riga, quella da mettere in colonna e quella da mettere tra i valori.

**Comment by ebergam** [comment]
@jenkin in locale, come la committo su ondata? Ne ho le permission? L'ho scaricata e modificata in locale, se puoi mettimi i comandi giusti su come pusharla qui, che stavo cercando come ma non voglio far cazzate :)

**Comment by ebergam** [comment]
@jenkin fatto da browser alla fine, prossima volta faccio fork e pull.. :)

**Comment by jenkin** [comment]
Clona il repo in locale, fai checkout sulla branch feature/[nome], lavora, poi commit e push. E poi avvisi di aver fatto.

**Comment by jenkin** [comment]
Vista, ottimo direi... :) Ho sistemato la struttura dell'html, ci sono alcuni problemi sulle librerie js che vengono caricate in chiusura del body, non le elimino perché temo che facciano funzionare il footer...

**Comment by ebergam** [comment]
@jenkin su questo bisogna chiedere a @nelsonmau, header e footer li ho presi dalla pagina "risorse"

**Comment by nelsonmau** [comment]
Grazie @jenkin ed @ebergam, ma questo è il repo del sito non degli strumenti.
Quindi please fate un altro repo con il tool togliendolo da qui, altrimenti quando cambiamo il sito, finisce anche questo in soffitta.
Grazie cari

**Comment by nelsonmau** [comment]
@jenkin btw notevolissimo il commento "l'ho implementata in pochi minuti", potremmo proporre comando --jenkin a git, prevedendo anche che il software fa un caffè :P

**Comment by jenkin** [comment]
@aborruso , secondo te è meglio fare un repo per ognuno di questi mini tool o farne uno solo da esporre sotto tools.ondata.it/[nome strumento] ?

**Comment by aborruso** [comment]
@jenkin ne farei soltanto uno da esporre sotto  tools.ondata.it/[nome strumento]

**Comment by nelsonmau** [comment]
io avrei delle issue da segnare, che intanto appunto segno qui

* aggiungere pulsante "Reverse" che esegue l'operazione
* aggiungere pulsante "scarica il risultato come csv"
* aggiungere dataset di esempio (almeno uno, con spiegazione)
* aggiungere spiegazione su come funziona
* scegliere layout e implementarlo
* ci vorrebbe anche screencast video per mostrare un utilizzo...

**Comment by jenkin** [comment]
Rispondo a @nelsonmau :

* no, l'operazione che dici tu è la tabella pivot, che richiede altri input da parte dell'utente: variabile di riga, di colonna, di valore, funzione di aggregazione, ecc. L'operazione che dici tu risponde a un'altra esigenza, se ci interessa farei proprio un altro tool, simile, ma diverso;
* ni, nel senso che allora ci vorrebbe anche un "carica csv", mentre per ora è pensato per tabella piccole per cui fai copia / incolla (da cui la scelta del TAB, che è il delimitatore naturale dei copia / incolla sui fogli di calcolo);
* c'è già nel placeholder, all'interno della textarea in grigio;
* da migliorare il testo di @ebergam;
* quello di @ebergam non è già sufficiente?
* chiederemo a qualcuno di farlo una volta on-line

Personalmente farei giusto qualche test e andrei subito on-line con questo che c'è...

**Comment by aborruso** [comment]
2017-02-27 11:01 GMT+01:00 Alessio Cimarelli <notifications@github.com>:

> Personalmente farei giusto qualche test e andrei subito on-line con questo
> che c'è...
>
>
I agree

___________________

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by ebergam** [comment]
@jenkin, assolutamente, il testo sotto l'ho proprio accennato, è da migliorare, ma si può fare in un secondo momento. Su tools.ondata.it/[nome strumento] anche per me è l'idea migliore.

**Comment by nelsonmau** [comment]
io non agree ma la democrazia regna.

please però, su un altro repo

chiudo la issue :)

**Comment by jenkin** [comment]
Nuovo repo: https://github.com/ondata/ondata-tool-pivot-reverser. On-line qui: http://tools.ondata.it/pivot-reverser/.
