### ISSUE TITLE
HomePage / Inserire riferimento a iscrizione registro delle non profit

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#37]
@giuragu ci dici la frase da inserire? la metterei nel footer.. 
(cc @lorenzoperone)

**Comment by giuragu** [comment]
Ciao @nelsonmau si,
"onData è iscritta al n. 295 del Registro regionale delle Associazioni di Promozione sociale (Sicilia)"

Va bene?

**Comment by giuragu** [comment]
ah appena aggiornato dovremmo spuntare  [qui](https://dati.regione.sicilia.it/dataset/elenco-delle-associazioni-di-promozione-sociale). Siamo iscritti dal 5/2 e il dataset è aggiornato a qualche giorno prima. Poi sarebbe utile inserire link

**Comment by nelsonmau** [comment]
@giuragu mettiamo la frase (e me la scrivi tu qui) oppure ignoriamo la cosa e chiudiamo la issue?

grazie!

**Comment by giuragu** [comment]
"Associazione iscritta al n. 295 del Registro regionale delle Associazioni di Promozione Sociale con D.R.S. n. 152 del 5/2/2019 (legge n. 383/2000 ed art. 64 l.r. n. 9/2015)"
ecco qui @nelsonmau

**Comment by ilacopperfild** [comment]
... Al registro della regione Sicilia delle associazioni di promozione
sociale...

Il ven 19 lug 2019, 09:33 Giuseppe Ragusa <notifications@github.com> ha
scritto:

**Comment by nelsonmau** [comment]
fatto grazie @ilacopperfild
