### ISSUE TITLE
Bilanci in pagina Chi siamo

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#38]
ciao, ho spostato i link ai bilanci in pagina chi siamo
https://ondata.it/contact.html

al momento sono disponibili:
- 2018
- 2017

@giuragu: puoi caricare in [questa cartella](https://github.com/ondata/ondatawebsite/tree/master/docs/bilanci) i precedenti? basta che li chiami `2016.pdf` e `2015.pdf`

quando hai fatto, chiudi anche questa issue please!
grazie :-)

**Comment by giuragu** [comment]
Ciao @nelsonmau 
2016 caricato. Sul 2015 devo passare un attimo da Arturo perché non ho copia.

**Comment by giuragu** [comment]
non è possibile caricare bilancio 2015. Cancellato link "2015". Chiudo issue
