### ISSUE TITLE
Homepage nuova su Coronavirus

### ISSUE THREAD

**Issue by nelsonmau** [ondata/ondatawebsite#42]
Ho creato in bozza questa homepage con un elenco di cose che stiamo facendo.
Mi elencate in basso altre attività da inserire o suggerimenti di modifiche? 

@aborruso @patrunomeister @lorenzoperone (e taggate chi volete)

![coronaondata3](https://user-images.githubusercontent.com/1769578/78037286-a1b65f00-736b-11ea-803a-d4f8e3914854.png)

**Comment by lorenzoperone** [comment]
Ciao @nelsonmau mi sembra una buona idea, c'è da correggere contattati=>contattaci

**Comment by Jaaapiii** [comment]
Mi sembra top! posso dare una mano in qualche modo?

**Comment by nelsonmau** [comment]
@JpTapo ho messo il tuo 

![coronaondata3](https://user-images.githubusercontent.com/1769578/78037406-cad6ef80-736b-11ea-8e42-41d1f633e0db.png)

**Comment by Jaaapiii** [comment]
Va un po' allineata meglio 😉 e non mettere i credits siamo sempre noi!

**Comment by nelsonmau** [comment]
Caro @JpTapo, 
Su questa frase:

> e non mettere i credits **siamo sempre noi**!

@aborruso piangerà un po'  <3

**Comment by nelsonmau** [comment]
@JpTapo scaricati la pagina e modifica come vuoi! o fallo su inspector e poi mi dai il css da cambiare!
