### ISSUE TITLE
Aggiornamento progetti

### ISSUE THREAD

**Issue by jenkin** [ondata/ondatawebsite#6]
Ci sono due tipi di progetti, quelli a lungo termine che permangono anche dopo la loro eventuale chiusura e hanno mezzi propri (confiscati bene, albopop, l'aria che tira, dati alla fiamme, ecc.), e quelli più volatili, spesso legati a eventi organizzati da ondata oppure in cui ondata è stata coinvolta (the big hack 2015, milano@work, ecc.).

Nella sezione "Progetti" separerei le due tipologie, magari con lo stesso criterio dei soci (un po' più grandi le tile della prima categoria con descrizione, più piccole e solo titolo, foto, link quelle della seconda).

**Comment by nelsonmau** [comment]
mah!
