### ISSUE TITLE
Mappa dei soci

### ISSUE THREAD

**Issue by jenkin** [ondata/ondatawebsite#9]
L'associazione è un gruppo delocalizzato in quasi tutta Italia, sarebbe carino aggiungere una sezione "Dove siamo" con una mappa dei soci.

**Comment by eccoilmoro** [comment]
Creata la mappa, alimentata dall'anagrafica soci su GDrive.
Creato il link in homepage.
https://umap.openstreetmap.fr/en/map/soci-ondata_121100#6/42.691/10.833
